# 这是一个注释示例
# 物品ID:
#   enabled: true # 是否启用
#   type: "shaped" # "shaped" 或 "shapeless"
#   shape: # 如果是 "shaped"，则需要此项
#     - "AAA"
#     - "A A"
#     - "AAA"
#   ingredients: # "shaped" 和 "shapeless" 都需要
#     A: "DIAMOND"
#   result: # 结果
#     material: "DIAMOND"
#     amount: 1
#     display_name: "显示的名字"
#     lore:
#       - "最好别动"
#     custom_model_data: 123456
#     projecte_id: "my_custom_item"

recipes:
  philosopher_stone:
    enabled: true
    type: "shaped"
    shape:
      - "RGR"
      - "GDG"
      - "RGR"
    ingredients:
      R: "REDSTONE"
      G: "GLOWSTONE_DUST"
      D: "DIAMOND"
    result:
      material: "POPPED_CHORUS_FRUIT"
      display_name: "item.philosopher_stone.name"
      lore:
        - "item.philosopher_stone.lore1"
        - "item.philosopher_stone.lore2"
        - "item.philosopher_stone.lore3"
      unbreakable: true

  philosopher_stone_alt:
    enabled: true
    type: "shaped"
    shape:
      - "GRG"
      - "RDR"
      - "GRG"
    ingredients:
      R: "REDSTONE"
      G: "GLOWSTONE_DUST"
      D: "DIAMOND"
    result:
      material: "POPPED_CHORUS_FRUIT"
      display_name: "item.philosopher_stone.name"
      lore:
        - "item.philosopher_stone.lore1"
        - "item.philosopher_stone.lore2"
        - "item.philosopher_stone.lore3"
      unbreakable: true

  transmutation_table:
    enabled: true
    type: "shaped"
    shape:
      - "OSO"
      - "SPS"
      - "OSO"
    ingredients:
      O: "OBSIDIAN"
      S: "STONE"
      P: "POPPED_CHORUS_FRUIT"
    result:
      material: "PETRIFIED_OAK_SLAB"
      display_name: "item.transmutation_table.name"

  transmutation_table_alt:
    enabled: true
    type: "shaped"
    shape:
      - "SOS"
      - "OPO"
      - "SOS"
    ingredients:
      O: "OBSIDIAN"
      S: "STONE"
      P: "PETRIFIED_OAK_SLAB"
    result:
      material: "ENCHANTED_BOOK"
      custom_model_data: 1
      display_name: "item.transmutation_table.name"

  alchemical_bag:
    enabled: true
    type: "shaped"
    shape:
      - "LDL"
      - "DCD"
      - "LDL"
    ingredients:
      L: "LEATHER"
      C: "CHEST"
      D: "DIAMOND_BLOCK"
    result:
      material: "LEATHER_HORSE_ARMOR"
      display_name: "item.alchemical_bag.name"

  dark_matter:
    enabled: true
    type: "shaped"
    shape:
      - "AAA"
      - "ADA"
      - "AAA"
    ingredients:
      A: "projecte:aeternalis_fuel"
      D: "DIAMOND_BLOCK"
    result:
      projecte_id: "dark_matter"

  red_matter_1:
    enabled: true
    type: "shaped"
    shape:
      - "AMA"
      - "AMA"
      - "AMA"
    ingredients:
      A: "projecte:aeternalis_fuel"
      M: "projecte:dark_matter"
    result:
      projecte_id: "red_matter"

  red_matter_2:
    enabled: true
    type: "shaped"
    shape:
      - "AAA"
      - "MMM"
      - "AAA"
    ingredients:
      A: "projecte:aeternalis_fuel"
      M: "projecte:dark_matter"
    result:
      projecte_id: "red_matter"

  dark_matter_block:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:dark_matter"
      - "projecte:dark_matter"
      - "projecte:dark_matter"
      - "projecte:dark_matter"
    result:
      projecte_id: "dark_matter_block"

  red_matter_block:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:red_matter"
      - "projecte:red_matter"
      - "projecte:red_matter"
      - "projecte:red_matter"
    result:
      projecte_id: "red_matter_block"

  dark_matter_block_decompose:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:dark_matter_block"
    result:
      projecte_id: "dark_matter"
      amount: 4

  red_matter_block_decompose:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:red_matter_block"
    result:
      projecte_id: "red_matter"
      amount: 4

  alchemical_bag_dyeing:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:alchemical_bag"
      - "any_dye"
    result:
      material: "LEATHER_HORSE_ARMOR"

  low_covalence_dust:
    enabled: true
    type: "shapeless"
    ingredients:
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "COBBLESTONE"
      - "CHARCOAL"
    result:
      projecte_id: "low_covalence_dust"
      amount: 40

  medium_covalence_dust:
    enabled: true
    type: "shapeless"
    ingredients:
      - "IRON_INGOT"
      - "REDSTONE"
    result:
      projecte_id: "medium_covalence_dust"
      amount: 40

  high_covalence_dust:
    enabled: true
    type: "shapeless"
    ingredients:
      - "DIAMOND"
      - "COAL"
    result:
      projecte_id: "high_covalence_dust"
      amount: 40

  low_divining_rod:
    enabled: true
    type: "shaped"
    shape:
      - "CCC"
      - "CSC"
      - "CCC"
    ingredients:
      C: "projecte:low_covalence_dust"
      S: "STICK"
    result:
      projecte_id: "low_divining_rod"

  medium_divining_rod:
    enabled: true
    type: "shaped"
    shape:
      - "CCC"
      - "CSC"
      - "CCC"
    ingredients:
      C: "projecte:medium_covalence_dust"
      S: "STICK"
    result:
      projecte_id: "medium_divining_rod"

  high_divining_rod:
    enabled: true
    type: "shaped"
    shape:
      - "CCC"
      - "CSC"
      - "CCC"
    ingredients:
      C: "projecte:high_covalence_dust"
      S: "STICK"
    result:
      projecte_id: "high_divining_rod"

  repair_talisman:
    enabled: true
    type: "shaped"
    shape:
      - "HML"
      - "SPS"
      - "LMH"
    ingredients:
      H: "projecte:high_covalence_dust"
      M: "projecte:medium_covalence_dust"
      L: "projecte:low_covalence_dust"
      S: "STRING"
      P: "PAPER"
    result:
      projecte_id: "repair_talisman"

  repair_talisman_alt:
    enabled: true
    type: "shaped"
    shape:
      - "LMH"
      - "SPS"
      - "HML"
    ingredients:
      H: "projecte:high_covalence_dust"
      M: "projecte:medium_covalence_dust"
      L: "projecte:low_covalence_dust"
      S: "STRING"
      P: "PAPER"
    result:
      projecte_id: "repair_talisman"

  klein_star_ein:
    enabled: true
    type: "shaped"
    shape:
      - "MMM"
      - "MDM"
      - "MMM"
    ingredients:
      M: "projecte:mobius_fuel"
      D: "DIAMOND"
    result:
      projecte_id: "klein_star_ein"

  klein_star_zwei:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:klein_star_ein"
      - "projecte:klein_star_ein"
      - "projecte:klein_star_ein"
      - "projecte:klein_star_ein"
    result:
      projecte_id: "klein_star_zwei"

  klein_star_drei:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:klein_star_zwei"
      - "projecte:klein_star_zwei"
      - "projecte:klein_star_zwei"
      - "projecte:klein_star_zwei"
    result:
      projecte_id: "klein_star_drei"

  klein_star_vier:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:klein_star_drei"
      - "projecte:klein_star_drei"
      - "projecte:klein_star_drei"
      - "projecte:klein_star_drei"
    result:
      projecte_id: "klein_star_vier"

  klein_star_sphere:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:klein_star_vier"
      - "projecte:klein_star_vier"
      - "projecte:klein_star_vier"
      - "projecte:klein_star_vier"
    result:
      projecte_id: "klein_star_sphere"

  klein_star_omega:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:klein_star_sphere"
      - "projecte:klein_star_sphere"
      - "projecte:klein_star_sphere"
      - "projecte:klein_star_sphere"
    result:
      projecte_id: "klein_star_omega"

  transmutation_tablet_book:
    enabled: true
    type: "shaped"
    shape:
      - "DSD"
      - "SPS"
      - "DSD"
    ingredients:
      D: "projecte:dark_matter_block"
      S: "STONE"
      P: "projecte:transmutation_table"
    result:
      projecte_id: "transmutation_tablet_book"

  # Dark Matter Tools
  dark_matter_pickaxe:
    enabled: true
    type: "shaped"
    shape:
      - "MMM"
      - " S "
      - " S "
    ingredients:
      M: "projecte:dark_matter"
      S: "DIAMOND"
    result:
      projecte_id: "dark_matter_pickaxe"

  dark_matter_axe:
    enabled: true
    type: "shaped"
    shape:
      - "MM "
      - "MS "
      - " S "
    ingredients:
      M: "projecte:dark_matter"
      S: "DIAMOND"
    result:
      projecte_id: "dark_matter_axe"

  dark_matter_shovel:
    enabled: true
    type: "shaped"
    shape:
      - " M "
      - " S "
      - " S "
    ingredients:
      M: "projecte:dark_matter"
      S: "DIAMOND"
    result:
      projecte_id: "dark_matter_shovel"

  dark_matter_hoe:
    enabled: true
    type: "shaped"
    shape:
      - "MM "
      - " S "
      - " S "
    ingredients:
      M: "projecte:dark_matter"
      S: "DIAMOND"
    result:
      projecte_id: "dark_matter_hoe"

  dark_matter_sword:
    enabled: true
    type: "shaped"
    shape:
      - " M "
      - " M "
      - " S "
    ingredients:
      M: "projecte:dark_matter"
      S: "DIAMOND"
    result:
      projecte_id: "dark_matter_sword"

  dark_matter_shears:
    enabled: true
    type: "shaped"
    shape:
      - " M"
      - "D "
    ingredients:
      M: "projecte:dark_matter"
      D: "DIAMOND"
    result:
      projecte_id: "dark_matter_shears"

  dark_matter_hammer:
    enabled: true
    type: "shaped"
    shape:
      - "DTD"
      - " T "
      - " T "
    ingredients:
      D: "projecte:dark_matter"
      T: "DIAMOND"
    result:
      projecte_id: "dark_matter_hammer"

  # Red Matter Tools
  red_matter_pickaxe:
    enabled: true
    type: "shaped"
    shape:
      - "RRR"
      - " T "
      - " S "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_pickaxe"
      S: "projecte:dark_matter"
    result:
      projecte_id: "red_matter_pickaxe"

  red_matter_axe:
    enabled: true
    type: "shaped"
    shape:
      - "RR "
      - "RT "
      - " S "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_axe"
      S: "projecte:dark_matter"
    result:
      projecte_id: "red_matter_axe"

  red_matter_shovel:
    enabled: true
    type: "shaped"
    shape:
      - " R "
      - " T "
      - " S "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_shovel"
      S: "projecte:dark_matter"
    result:
      projecte_id: "red_matter_shovel"

  red_matter_hoe:
    enabled: true
    type: "shaped"
    shape:
      - "RR "
      - " T "
      - " S "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_hoe"
      S: "projecte:dark_matter"
    result:
      projecte_id: "red_matter_hoe"

  red_matter_sword:
    enabled: true
    type: "shaped"
    shape:
      - " R "
      - " R "
      - " T "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_sword"
    result:
      projecte_id: "red_matter_sword"

  red_matter_shears:
    enabled: true
    type: "shaped"
    shape:
      - " R"
      - "T "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_shears"
    result:
      projecte_id: "red_matter_shears"

  red_matter_hammer:
    enabled: true
    type: "shaped"
    shape:
      - "RDR"
      - " T "
      - " D "
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_hammer"
      D: "projecte:dark_matter"
    result:
      projecte_id: "red_matter_hammer"

  # Dark Matter Armor
  dark_matter_helmet:
    enabled: true
    type: "shaped"
    shape:
      - "MMM"
      - "M M"
    ingredients:
      M: "projecte:dark_matter"
    result:
      projecte_id: "dark_matter_helmet"

  dark_matter_chestplate:
    enabled: true
    type: "shaped"
    shape:
      - "M M"
      - "MMM"
      - "MMM"
    ingredients:
      M: "projecte:dark_matter"
    result:
      projecte_id: "dark_matter_chestplate"

  dark_matter_leggings:
    enabled: true
    type: "shaped"
    shape:
      - "MMM"
      - "M M"
      - "M M"
    ingredients:
      M: "projecte:dark_matter"
    result:
      projecte_id: "dark_matter_leggings"

  dark_matter_boots:
    enabled: true
    type: "shaped"
    shape:
      - "M M"
      - "M M"
    ingredients:
      M: "projecte:dark_matter"
    result:
      projecte_id: "dark_matter_boots"

  # Red Matter Armor
  red_matter_helmet:
    enabled: true
    type: "shaped"
    shape:
      - "RRR"
      - "RTR"
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_helmet"
    result:
      projecte_id: "red_matter_helmet"

  red_matter_chestplate:
    enabled: true
    type: "shaped"
    shape:
      - "RTR"
      - "RRR"
      - "RRR"
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_chestplate"
    result:
      projecte_id: "red_matter_chestplate"

  red_matter_leggings:
    enabled: true
    type: "shaped"
    shape:
      - "RRR"
      - "RTR"
      - "R R"
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_leggings"
    result:
      projecte_id: "red_matter_leggings"

  red_matter_boots:
    enabled: true
    type: "shaped"
    shape:
      - "RTR"
      - "R R"
    ingredients:
      R: "projecte:red_matter"
      T: "projecte:dark_matter_boots"
    result:
      projecte_id: "red_matter_boots"

  alchemical_coal:
    enabled: true
    type: "shapeless"
    ingredients:
      - "COAL"
      - "COAL"
      - "COAL"
      - "COAL"
      - "POPPED_CHORUS_FRUIT"
    result:
      projecte_id: "alchemical_coal"

  mobius_fuel:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:alchemical_coal"
      - "projecte:alchemical_coal"
      - "projecte:alchemical_coal"
      - "projecte:alchemical_coal"
      - "POPPED_CHORUS_FRUIT"
    result:
      projecte_id: "mobius_fuel"

  aeternalis_fuel:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:mobius_fuel"
      - "projecte:mobius_fuel"
      - "projecte:mobius_fuel"
      - "projecte:mobius_fuel"
      - "POPPED_CHORUS_FRUIT"
    result:
      projecte_id: "aeternalis_fuel"

  aeternalis_to_mobius:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:aeternalis_fuel"
      - "POPPED_CHORUS_FRUIT"
    result:
      projecte_id: "mobius_fuel"
      amount: 4

  mobius_to_alchemical:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:mobius_fuel"
      - "POPPED_CHORUS_FRUIT"
    result:
      projecte_id: "alchemical_coal"
      amount: 4

  alchemical_to_coal:
    enabled: true
    type: "shapeless"
    ingredients:
      - "projecte:alchemical_coal"
      - "POPPED_CHORUS_FRUIT"
    result:
      material: "COAL"
      amount: 4